disabled_rules:
  - trailing_whitespace
included:
  - lpaandco
excluded:
  - lpaandco/Sourcery

line_length:
  warning: 200
  error: 600
identifier_name:
  validates_start_with_lowercase: false
  min_length:
    warning: 3
  max_length:
    warning: 50
# force_cast:
#   severity: warning
# force_try:
#   severity: warning
